config/routes.rb
Rails.application.routes.draw do
  namespace :feed do
    get 'post/index'
  end
  namespace :site do
    get 'users/index'
  end
  namespace :hub do
    get 'login/index'
  end
  namespace :feed do
    resources :home, execpt: [:edit, :index]
    resources :users
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    resources :posts
    post '/likes/:post_id', to: 'posts#like', as: "like"
    root 'posts#index'
  end
  namespace :site do
    get  'welcome/index'
    resources :users
    post '/users/register'
  end

  devise_for :users
 
  get 'inicio', to: 'hub/login#index'
  
  root to: 'hub/login#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
      belongs_to :user

end

app/models/post.rb
  class Post < ApplicationRecord
      has_many :likes
      belongs_to :user



  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :post
 has_many :like
 has_one :user_profile
 accepts_nested_attributes_for :user_profile, reject_if: :all_blank
     

  #Validates
  validates :first_name, :last_name, presence: true, length: {minimum: 3}


  def  full_name
 [ self.first_name,self.last_name].join(' ') 


         	
   end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feed/home_controller.rb
class Feed::HomeController < FeedController
  before_action :set_user

  def index
    @user.build_user_profile if @user.user_profile.blank?      
    @posts = Post.all.order(created_at: :desc)
  end

  def new   
    @post = Post.new
  end

  def create

    @post = Post.new post_params.merge(user: @user)

      if @post.save
        redirect_to feed_home_index_path
      end
    end

  private
  def post_params
    params.require(:post).permit(:post, :user,)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end 

app/controllers/feed/posts_controller.rb
class Feed::PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def like
    post = Post.find(params[:post_id]) 
    like_count = post.like_count
    like = current_user.like.find_by(post_id: post.id)

    if like.blank?
      new_like = Like.new(post_id: post.id, user_id: current_user.id)
      post.update(like_count: like_count += 1)
      new_like.save
    else
      Like.destroy(like.id)
      post.update(like_count: like_count -= 1)
    end
    redirect_to feed_home_index_path
  end



  private
  def post_params
    params.require(:post).permit(:post, :user, :like)
  end
end

app/controllers/feed/profile_controller.rb
class Feed::ProfileController < FeedController
  before_action :verify_password, only: [:update]
  before_action :set_user
  
  def edit
    @user.build_user_profile if @user.user_profile.blank?
  end

  def update
    if @user.update(params_user)
        redirect_to feed_home_index_path  , notice: "Usuário atualizado com sucesso!"
    else
      render :edit
    end    
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
      user_profile_attributes: [:id, :address, :gender, :birthdate, :avatar])
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
	before_action :authenticate_user!

end

app/controllers/hub/login_controller.rb
class Hub::LoginController < SiteController 
  def index
  end
end

app/controllers/site/users_controller.rb
class Site::UsersController < ApplicationController
  before_action :password_verify, only: [:update]
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
  	@users = User.all.page
  end

  def new
  	@user = User.new
  end

   def register
    @user = User.new(params_user)
    if @user.save
      redirect_to feed_home_index_path, notice: "Usuario Criado com sucesso"
    else
      redirect_to feed_home_index_path
    end
 end

 def update
    if @user.update(params_user)
    	redirect_to feed_home_index_path, notice: "Usuario Atualizado com sucesso"
    else
    	render :edit
    end
  end


  def params_user
    params_user = params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :nick_name, :avatar)
  end

 def destroy
    if @user.destroy
      redirect_to site_welcome_index_path, notice: "Usuario deletado com sucesso"
    else
      render :index
    end
 end

  def password_verify
     if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
     params[:user].extract!(:password, :password_confirmation)
   end
 end

   def set_user
    @user = User.find(params[:id])
   end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout 'site'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed/home_helper.rb
module Feed::HomeHelper
end

app/helpers/feed/posts_helper.rb
module Feed::PostsHelper
end

app/helpers/feed/profile_helper.rb
module Feed::ProfileHelper

def gender_select(user, current_gender)
 user.user_profile.gender == current_gender ? 'btn-primary' : 'btn-default'
  end
end

app/helpers/feed_helper.rb
module FeedHelper

end

app/helpers/hub/login_helper.rb
module Hub::LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/site/user_helper.rb
module Site::UserHelper
end

app/helpers/site/users_helper.rb
module Site::UsersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/feed/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lame Book</title>
</head>

<body style="background-color: white">




  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:  #cd9557!important">
    <a class="navbar-brand" href="#">Lame Book</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <% if @user.user_profile.avatar.attached? %>
          <%= image_tag @user.user_profile.avatar, height: 50, width: 50, class: "rounded-circle"%>
          <% else %>  
          <%= image_tag gravatar_image_url(@user.email, size: 50), height: 50, width: 50, class: "rounded-circle"%>
          <% end %>
          <%= link_to("#{ current_user.full_name}",  feed_profile_path ) %>
        </div>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
     <%= link_to(destroy_user_session_path, method: :delete) do %>
     <span style="color: white">Sair</span> 
     <i style="color: white" class="fas fa-sign-out-alt" ></i>
     <% end %>
   </div>
 </div>
</nav>

</body>

<div class="jumbotron jumbotron-fluid" style="margin-left: 4%; margin-right: 4%">
  <div class="container">
    <%= form_with(model: @post, scope: :post, format: :json, id: 'post-form') do |form| %>
    <div class="field"><h2>Pronto pra fazer um novo post?</h2>
      <%= form.text_area :post, id: :post, class: "form-control post-textarea", required: true %>
      <%= form.hidden_field :user, id: :user %>
    </div>
    <div class="actions text-right"> 
      <input type="submit" name="commit" value="Publicar"  class="btn btn-default submit" style="float: none;margin-right: 4%;width: 12%; margin-top: 1%;color: #FFF;background-color: #c99128;" data-disable-with="Cadastrar-se">
    </div>
    <% end %>
  </div>
  <div class="posts mt-5">
    <% @posts.each do |post| %>
    <div class="post-wrapper col-12 mb-2 p-0">
      <div class="card">
        <div class="card-header">
          <%= post.user.full_name%>
          <small class="float-right mt-1"><%= post.created_at.strftime("at %I:%M%p") %></small>
        </div>
        <div class="card-body">
          <p class="card-text"><%= post.post %></p>
          <%= link_to '', feed_like_path(post_id: post.id), remote: true, method: :post, class: "far fa-thumbs-up add-like" %><span class="ml-2" data-post="<%= post.id %>"><%= post.like_count[0] %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</nav>
</html> 

app/views/feed/posts/create.html.erb
<h1>Feed::Posts#create</h1>
<p>Find me in app/views/feed/posts/create.html.erb</p>

app/views/feed/posts/new.html.erb
<h1>Feed::Posts#new</h1>
<p>Find me in app/views/feed/posts/new.html.erb</p>

app/views/feed/profile/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Perfil</title>
</head>

<body style="
background-image: url('<%= image_path('users edit.jpg') %>');
background-repeat: no-repeat;
width: 100%;
height: 85%;
background-size: cover;">



<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:  #cd9557!important">
  <a class="navbar-brand" href="#">Perfil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a style="color: white"><%= current_user.full_name %></a>
      </div>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
   <%= link_to(feed_home_index_path) do %>
   <i style="color: white"  class="fas fa-backspace"></i> 
   <span style="color: white">Voltar</span> 

   <% end %>
 </form>
</div>

</nav>

<div style="width: 50%; margin-left: 25%; margin-top: 2%">
  <%= form_with(url: feed_profile_path, model: @user , local: true, class:"form-horizontal form-label-left") do |form| %>
  <%= form.fields_for :user_profile do |profile_form|  %>
<div class="card">
  <div class="card-body">
  <div class="form-group">
    <div class="row">
      <div class="col-sm-4">
       <% if @user.user_profile.avatar.attached? %>
       <%= image_tag @user.user_profile.avatar, height: 100, width: 100, class: "rounded-circle"%>
       <% else %>  
       <%= image_tag gravatar_image_url(@user.email, size: 100), height: 100, width: 100, class: "rounded-circle"%>
       <% end %>
     </div>

     

     <div class="col-sm-8" style="margin-left: 14%">
      <%= profile_form.file_field :avatar %>
    </div>
  </div>
</div>             


    <%= form.label :Nick, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= form.text_field :nick_name, class:"form-control col-md-7 col-xs-12" %>


    <%= form.label :Nome, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= form.text_field :first_name, class:"form-control col-md-7 col-xs-12" %>



    <%= form.label :Sobrenome, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= form.text_field :last_name, class:"form-control col-md-7 col-xs-12" %>


    <%= form.label :Email, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= form.text_field :email, class:"form-control col-md-7 col-xs-12", readonly: true  %>




    <%= profile_form.label :Endereço, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= profile_form.text_field :address, class:"form-control col-md-7 col-xs-12"%>



    <%= profile_form.label :Sexo, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-7 col-sm-6 col-xs-12">
      <div id="gender" class="btn-group" data-toggle="buttons">
        <label class="btn <%= gender_select(@user, 'M') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default" style="color: white">
          <%= profile_form.radio_button :gender, "M", "data-parsley-multiple":"gender"%> &nbsp; Masculino &nbsp;
        </label>
        <label class="btn <%= gender_select(@user, 'F') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default"style="color: white">
          <%= profile_form.radio_button :gender, "F", "data-parsley-multiple":"gender"%> &nbsp; Feminino &nbsp;
        </label>
      </div>
    </div>



    <%= profile_form.label :Data_De_Nascimento, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
    <%= profile_form.date_field :birthdate, value: (l(@user.user_profile.birthdate) unless @user.user_profile.birthdate.blank?), class:"form-control col-md-7 col-xs-12 datepicker"%>


    <% end %>


    <input type="submit" name="commit" value="Salvar"  class="btn btn-default submit" style="float: none;margin-left: 46%;width: 11%;color: #FFF;background-color: #c99128; margin-top: 1%" data-disable-with="Salvar"> 
    <% end %>


  </div>
  <%= javascript_tag do %>
  var labels = document.querySelectorAll('div#gender label');

  labels.forEach((label) => {
  label.addEventListener('click', () => {
  label.classList.remove('btn-default');
  label.classList.add('btn-primary');

  labels.forEach((lbl) => {
  if(lbl !== label){
  lbl.classList.remove('btn-primary');
  lbl.classList.add('btn-default');
};
});
});
});
<% end %>




</div>
</div>
</body>



</html> 

app/views/feed/profile/update.js.erb
$('#avatarModal').modal('hide');

document.getElementById('imgAvatarLg').src = "<%= url_for(@user.user_profile.avatar) %>"
document.getElementById('imgAvatarMd').src = "<%= url_for(@user.user_profile.avatar) %>"
document.getElementById('imgAvatarSm').src = "<%= url_for(@user.user_profile.avatar) %>"

$.bootstrapGrowl('Avatar atualizado com sucesso!', {
  type: 'success', // (null, 'info', 'danger', 'success')
  align: 'right', // ('left', 'right', or 'center')
  allow_dismiss: true, // If true then will display a cross to close the popup.
  stackup_spacing: 10 // spacing between consecutively stacked growls.
});

app/views/site/users/index.html.erb
<h1>Site::Users#index</h1>
<p>Find me in app/views/site/users/index.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>